name: GitHub - Activity - Readme

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: jamesgeorge007/github-activity-readme@master
        name: update activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: yarn setup
        uses: DerYeger/yarn-setup-action@v1.0.1
        with:
          # The version of Node.js that will be used
          node-version: 18
      # update assets
      - uses: actions/checkout@v3
        with:
          repository: domechn/asset-statistics@master
          path: asset-statistics
      - run: |
          yarn
          yarn build
          env
          yarn gen -o $WORKFLOW_PATH/assets.svg
        name: update assets
        working-directory: asset-statistics
